config/routes.rb
Rails.application.routes.draw do


  # ログインしてない時のパス
  root  "static_pages#home"

  get '/users/show',   to: "users#show"
  get "/users/edit",   to: "users#edit"
  get "/signup",       to: "users#new"
  post "/signup",      to: "users#create"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    resources :photos, only: [:create]

    resources :likes, only: [:create, :destroy], shallow: true

    resources :comments, only: [:index, :create, :destroy], shallow: true

  end
  resources :relationships,       only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy

  has_many :likes, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, -> { order(:created_at => :desc) }, dependent: :destroy

  def liked_by(user)
    # user_idとpost_idが一致するlikeを検索する
    Like.find_by(user_id: user.id, post_id: id)
  end

  def is_belongs_to?(user)
    Post.find_by(user_id: user.id, id: id)
  end

  def self.search(search) #ここでのself.はMicropost.を意味する
    if search
      where(['caption LIKE ?', "%#{search}%"]) #検索とcontentの部分一致を表示。Micropost.は省略。
    else
      all #全て表示。Micropost.は省略。
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:show, :destroy]

  def index
    @posts = Post.limit(10).includes(:photos, :user, :likes).order('created_at DESC')
    @posts = Post.search(params[:search]).order('created_at DESC')
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      if params[:images]
        params[:images].each do |img|
          @post.photos.create(image: img)
        end
      end

      redirect_to posts_path
      flash[:notice] = "投稿が保存されました"
    else
      redirect_to posts_path
      flash[:alert] = "投稿に失敗しました"
    end
  end


  def show
    @photos = @post.photos
    @likes = @post.likes.includes(:user)
  end

  def destroy
    if @post.user == current_user
      return flash[:notice] = "投稿が削除されました" if @post.destroy
      flash[:alert] = "削除に失敗しました"
    end
    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:caption).merge(user_id: current_user.id)
    end

    def set_post
      @post = Post.find_by(id: params[:id])
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-2">
    <% if comment.user == current_user %>
      <%= link_to "", comment_path(comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <span>
      <strong>
        <%= link_to comment.user.name, user_path(comment.user), class: "no-text-decoration black-color" %>
      </strong>
    </span>
    <span><%= comment.comment %></span>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.name %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.name %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.name %>
    <% else %>
      <%= like.user.name + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/_post_list.html.erb
<% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>

          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

           <% if post.is_belongs_to? current_user %>
            <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>
        </div>

        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>

        <div class="card-body">
          <div class="row parts">

            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", like_path(post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>

            <%= link_to "", "#", class: "comment" %>
          </div>

          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>

          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>

            <%#==========ここから編集する========== %>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_for [post, Comment.new], html: { class: "w-100" }, remote: true do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>
            <%#==========ここまで編集する========== %>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, 'All posts') %>
<%= stylesheet_link_tag "custom", :media => "all" %>

<div id="posts">
  <% @posts.each do |post| %>
  <div class="col-md-8 col-md-2 mx-auto">
    <div class="card-wrap">
      <div class="card">
        <div class="card-header align-items-center d-flex">
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>

          <% end %>
          <%= link_to user_path(post.user), class: "black-color no-text-decoration",
            title: post.user.name do %>
            <strong><%= post.user.name %></strong>
          <% end %>

           <% if post.is_belongs_to? current_user %>
            <%= link_to post_path(post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
              <div class="delete-post-icon">
              </div>
            <% end %>
          <% end %>
        </div>

        <%= link_to(post_path(post)) do %>
          <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
        <% end %>

        <div class="card-body">
          <div class="row parts">

            <div id="like-icon-post-<%= post.id.to_s %>">
              <% if post.liked_by(current_user).present? %>
                <%= link_to "いいねを取り消す", like_path(post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
              <% else %>
                <%= link_to "いいね", post_likes_path(post), method: :POST, remote: true, class: "love hide-text" %>
              <% end %>
            </div>

            <%= link_to "", "#", class: "comment" %>
          </div>

          <div id="like-text-post-<%= post.id.to_s %>">
            <%= render "like_text", { likes: post.likes } %>
          </div>

          <div>
            <span><strong><%= post.user.name %></strong></span>
            <span><%= post.caption %></span>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post), class: "post-time no-text-decoration" %>

            <%#==========ここから編集する========== %>
            <div id="comment-post-<%= post.id.to_s %>">
              <%= render 'comment_list', { post: post } %>
            </div>
            <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),
              class: "light-color post-time no-text-decoration" %>
            <hr>
            <div class="row actions" id="comment-form-post-<%= post.id.to_s %>">
              <%= form_for [post, Comment.new], html: { class: "w-100" }, remote: true do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>
            <%#==========ここまで編集する========== %>

          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<% provide(:title, 'upload') %>
<div class="d-flex flex-column align-items-center mt-3">
  <div class="col-xl-7 col-lg-8 col-md-10 col-sm-11 post-card">
    <div class="card">
      <div class="card-header">
        投稿画面
      </div>
      <div class="card-body">
        <%= form_for @post, html: { multipart: true, class: "upload-images p-0 border-0" } do |f| %>
          <div class="form-group row mt-2">
            <div class="col-auto pr-0">
            <%# avatar入れる %>
            </div>
            <div class="col pl-0">
              <%= f.text_field :caption, class: "form-control border-0", placeholder: "キャプションを書く" %>
            </div>
          </div>
          <div class="mb-3">
            <%= file_field_tag "images[]", type: :file, multiple: false %>
          </div>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, 'post') %>
<div class="col-md-10 col-md-offset-1 mx-auto postShow-wrap">
  <div class="row post-wrap">
    <div class="col-md-8">
      <div class="card-left">
        <%= image_tag @post.photos.first.image.url(:medium), class: "card-img-top" %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card-right">
        <div class="card-right-comment">
          <div class="card-right-name d-flex">
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
            <% end %>
            <%= link_to user_path(@post.user), class: "black-color no-text-decoration",
              title: @post.user.name do %>
              <strong><%= @post.user.name %></strong>
            <% end %>

            <% if @post.is_belongs_to? current_user %>
              <%= link_to post_path(@post), method: :delete, class: "ml-auto mx-0 my-auto" do %>
                <div class="delete-post-icon">
                </div>
              <% end %>
            <% end %>
          </div>
          <div class="comment-post-id">
            <div class="m-2">
              <div id="comment-post-<%= @post.id.to_s %>">
                <%= render 'comment_list', post: @post %>
              </div>
            </div>
          </div>
        </div>
        <div class="row parts">
          <div id="like-icon-post-<%= @post.id.to_s %>">
            <% if @post.liked_by(current_user).present? %>
              <%= link_to "いいねを取り消す", like_path(@post.liked_by(current_user)), method: :DELETE, remote: true, class: "loved hide-text" %>
            <% else %>
              <%= link_to "いいね", post_likes_path(@post), method: :POST, remote: true, class: "love hide-text" %>
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= @post.id.to_s %>">
          <%= render "like_text", { likes: @likes } %>
        </div>
        <div class="post-time"><%= time_ago_in_words(@post.created_at).upcase %>前</div>
        <hr>
        <div class="row parts" id="comment-form-post-<%= @post.id.to_s %>">
          <%= form_for [@post, Comment.new], html: { class: "w-100" }, remote: true do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :post_id, value: @post.id %>
            <%= f.text_field :comment, class: "form-control comment-input border-0", placeholder: "コメント ...", autocomplete: :off %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>